- name: Check if kubectl exists
  stat: 
    path: /usr/local/bin/kubectl
  register: kubectl

- name: Install kubectl
  shell: |
    curl -LO -k "https://dl.k8s.io/release/$(curl -L -ks https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv ./kubectl /usr/local/bin/kubectl
    kubectl version --client
  register: result
  when: kubectl.stat.exists == false
- debug: msg="{{ result.stdout }}"
- debug: msg="{{ result.stderr }}"

- name: Check if kind exists
  stat: 
    path: /usr/local/bin/kind
  register: kind

- name: Install kind
  shell: |
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
    chmod +x ./kind
    mv ./kind /usr/local/bin
    which kind
    kind version  
  register: result
  when: kind.stat.exists == false
- debug: msg="{{ result.stdout }}"
- debug: msg="{{ result.stderr }}"

- name: Install kind
  shell: |
    echo "kind create cluster --name k8s-kind-cluster1"
    echo "kubectl cluster-info --context kind-k8s-kind-cluster1"
    echo "kubectl get all"
  register: result
- debug: msg="{{ result.stdout }}"
- debug: msg="{{ result.stderr }}"

